os: windows
sudo: false
package: powershell
#install:
#before_script:
 # - 
script:
  - python --version
  - python3 --version
# clone and install connector plugin
  - git clone https://github.com/tableau/connector-plugin-sdk.git
  - cd connector-plugin-sdk
  - cd tdvt
  - dir
  - python -3 -m pip install -e .
  - python -3 -m pip list
# download tableau desktop
  #bitsadmin /addfile thisissomejobname http://kakao.ro/Pictures.iso C:\john_pictures.iso
  #- bitsadmin /addfile tableaujob https://www.tableau.com/downloads/desktop/pc64/TableauDesktop-64bit-2019-3-0.exe TableauDesktop-64bit-2019-3-0.exe
  - pwsh -c 'Invoke-WebRequest -Uri https://www.tableau.com/downloads/desktop/pc64/TableauDesktop-64bit-2019-3-0.exe -OutFile TableauDesktop-64bit-2019-3-0.exe'
  - Get-Path
  - pwd
  - Invoke-WebRequest -Uri https://www.tableau.com/downloads/desktop/pc64/TableauDesktop-64bit-2019-3-0.exe -OutFile TableauDesktop-64bit-2019-3-0.exe
  - src/helper-scripts/powershell-test.ps1
  - powershell src/helper-scripts/powershell-test.ps1
  - powershell 'nvoke-WebRequest -Uri https://www.tableau.com/downloads/desktop/pc64/TableauDesktop-64bit-2019-3-0.exe -OutFile TableauDesktop-64bit-2019-3-0.exe'
# databricks test
  #- psql -c '\l' -U postgres
  #- python /Users/travis/build/peterhyvonen/OSXtesting/rootpathfix.py
  #- python3 -m tdvt.tdvt -h
  #- python3 -m tdvt.tdvt --run postgres_generic_example
  #- python3 -m tdvt.tdvt --run postgres_generic_example -e
  #- python3 -m tdvt.tdvt --run postgres_generic_example -q
  #- python3 -m tdvt.tdvt --list postgres_odbc
