os: windows
language: shell
script:
# test and setup Python
  - python --version
  - choco install python3 --params "/InstallDir:C:\Program Files\Python3"
  - pwd
  - export "PATH=/C/Program Files/Python3:$PATH"
  - python --version
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - dir "C:\Program Files\Python3"
  - echo "C:\Program Files\Python3\Lib"
  - dir "C:\Program Files\Python3\Lib"
  - echo "C:\Program Files\Python3\Tools"
  - dir "C:\Program Files\Python3\Tools"	
  - echo "C:\Program Files\Python3\Scripts"
  - dir "C:\Program Files\Python3\Scripts"		
  - pip3 --version
  - pip --version
  - powershell Get-ChildItem -Path C:\ -Filter pip* -Recurse -ErrorAction SilentlyContinue -Force
# clone and install connector plugin
  - git clone https://github.com/tableau/connector-plugin-sdk.git
  - cd connector-plugin-sdk
  - cd tdvt
  - dir
  - py -3 setup.py sdist --formats gztar
  - py -3 -m pip install tdvt-1.1.59.zip
  - python -3 -m pip install -e
  - python -3 -m pip list
  - sleep 10
# download tableau desktop
  - cd ..
  - cd ..
  - powershell Invoke-WebRequest -Uri https://www.tableau.com/downloads/desktop/pc64 -OutFile TableauDesktop-64bit-2019-3-0.exe
  - pwd
  - ls -l
  - .\TableauDesktop-64bit-2019-3-0.exe /quiet /norestart ACCEPTEULA=1
  # databricks test
  #- psql -c '\l' -U postgres
  #- python /Users/travis/build/peterhyvonen/OSXtesting/rootpathfix.py
  #- python3 -m tdvt.tdvt -h
  #- python3 -m tdvt.tdvt --run postgres_generic_example
  #- python3 -m tdvt.tdvt --run postgres_generic_example -e
  #- python3 -m tdvt.tdvt --run postgres_generic_example -q
  #- python3 -m tdvt.tdvt --list postgres_odbc
